import type { SheetType, PointScope } from '@/lib/domain/types';

export type SeedProduct = {
  name: string;
  sheetType: SheetType;
  pointScope: PointScope;
  shelfLifeDays?: number;
  aliases?: string[];
};

// Каталог: ручные имена с реальных листов + полное меню из iiko (отчёт 2026-06-08).
export const SEED_CATALOG: SeedProduct[] = [
  // --- ядро с рукописных листов (точные формулировки) ---
  { name: 'Самса', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Перемяч', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Беляш татарский', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирожок зел лук и яйцо', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирожок с картошкой', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирожок с капустой', sheetType: 'pies', pointScope: 'point1', aliases: ['Пирожок (беккен) с капустой'] },
  { name: 'Пирожок с печенью', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пицца закрытая', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пицца барбекю', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пицца открытая', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пицца сырная', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пицца куриная', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Сосиска в тесте', sheetType: 'pies', pointScope: 'point1', aliases: ['Сосиска в тексе'] },
  { name: 'Хачапури', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Хот-дог', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Ватрушка', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Творожники', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Кекс домашний', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Манго Маракуйя', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Клубничное облако', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Каскейл Сникерс', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Красный бархат', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Медовик Карамель', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Чизкейк клубничный', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5, aliases: ['Чизкейл клубничный'] },
  { name: 'Бенто Орео', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Зимняя вишня', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Эстерхази', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Тарт', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  // --- полное меню iiko ---
  { name: 'Пицца Классическая', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Беккен с капустой', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Корзиночка Жульен (Кур/Гриб)', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирожок зелёный лук/яйцо', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Перемяч (беляш)', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пицца Сыр Грибы', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Эскимо', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Сочень с творогом', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирожок с Яблоком', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Сосиска Провансаль', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Творожники', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Пирожок Сосиска+Картошка', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Хот-Дог NEW', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пицца Рожок', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Эклер Пломбирный', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Чоко-пай', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Твиксик', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Слойка курица/сыр', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Круассан вареная сгущёнка', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Кулич Творожный 500гр', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Самса со свининой', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Треугольник с курицей и картошкой', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Слойка ветчина сыр', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Круассан Черника', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Круассан малина', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Чизкей клубничный (кусочками)', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Кулич Творожный 300гр', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пончики на сметане', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Плюшка московская', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Чоко-пай клубничный', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Кекс', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Безе', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Капкейк ваниль клубника', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Капкейк Сникерс', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Корзиночка мини-сметанник', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Пикантная', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Медовик Карамельный (кусочками)', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Торт бамбл гам', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Пончик с Сах. Пудрой', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Пирожок Вишня', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Круассан Клубника', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Круассан Вишня', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Тарт Карамель Фундук', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Шоколадный чизкей бол', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Безе снеговик', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Эскимо в упаковке 1 сентября', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Трайфл Дамский каприз', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Трайфл клубничные', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Медовик шоколадный', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Капуста с мясом', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Медово-карамельный десерт с орехами', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'муссовая клубника', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Сникерс (бенто 900гр)', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Капкейк с картинкой', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'муссовый сникерс', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Клубничный (бенто 900гр)', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Бенто Черника-Малина', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Трайфл красный бархат с вишней', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Бенто Манго-Клубника', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Красный бархат (бенто 900гр)', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Шоколад Вишня (бенто 900гр)', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Постный картошка грибы', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Трайфл манго маракуйя', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Батон', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Постный лук грибы', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Трайфл тирамису', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'муссовая фисташка', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'муссовая черника', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Орео бенто (900гр)', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Пирог Жульен', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Зерновой', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирожок с горбуша/брокколи', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Бенто медовик', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Отрубной', sheetType: 'pies', pointScope: 'point1' },
  { name: 'муссовый апельсин', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Постный капуста с грибами', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирог Горбуша/брокколи', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Трайфл Сникерс', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Белый Хлеб', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирог Яблоко/корица', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Киш ветчина/грибы', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Капкейк манго маракуйя', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Косичка с маком', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирог Вишня', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирог КАЛЬЦОНЕ', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Киш брокколи чеснок', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Трайфл Шоколад- Малина', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Пирог Мясо/капуста', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Киш курица/лук', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Бенто медовик вишневый', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Пирог Клубника', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Беляш', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Трайфл киви клубника', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Шоколадный (бенто)', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Шоколадный чизкей мал', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Корзиночка Грибная', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пицца Пеперони', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Треугольник с мясом', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Безе елочка', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Бенто манго сметанна', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Бенто муссовый', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Дамские пальчики', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Заводной апельсин', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Зимняя вишня (бенто)', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Капкейк красный бархат', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Карамельный медовик (бенто) 800гр', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Клубничный', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Клубничое сердце', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Макаруны апельсин', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Макаруны клубника', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Макаруны смородина', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Малиновый тарт', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Маршмеллоу', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Медово карамельное сердце', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Морковно пряный десерт', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'муссовое сердечко', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'муссовое сердечко большое', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Набор 8 марта', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Набор Новогодний', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Набор Хэллоуин', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Наполеон', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Орео', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Павлова', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Профитоль Малина-Фисташка', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Профитроли с фундуком', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Птичье молоко', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Сердечко', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Торт Кофейный', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Трайфл апельсиновы медовик', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Трайфл капучино фундук', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Трайфл Орео', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Трайфл с картинкой', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Тропическая роза', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Чизкей (баночка) Карамель', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Чизкей (баночка) Манго Маракуйя', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Чизкей (баночка) Матча Латте', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Чизкей (баночка) Орео', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Чизкей (баночка) Фисташка Малина', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Чизкейк Крем-Брюле', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Чизкейк фисташка', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'ШУ', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Эклер карамельный', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Эклер с варенной сгущенкой', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Эклер Шоколадный', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Эскимо 3 шоколада', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Эскимо капучино фундук', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Эскимо клубничное', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Эскимо медвеженок', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Эскимо новогоднее', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Эскимо Орео', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Эскимо сердце', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Эскимо снеговик', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Эскимо черная смородина', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Ягодный микс 1кг', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Ягодный микс 400гр', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Багет', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Батон с чесноком и сыром', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Бородинский', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Булочка для бургера 75р', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Вишня', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Гречневый вкус', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Коржик молочный', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Королевская ватрушка', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Круассан (без начинки)49р', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Круассан Банан', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Круассан Лимон', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Круассан манго', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Круассан с абрикосом', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Круассан с Шоколадом', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Круассан черная смородина', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Кулич 300гр', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Кулич 500гр', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Луковый багет', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Маффины', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Отрубной, гречневый, зерновой', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирожное песочное Абрикос', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Пирожное песочное Банан', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Пирожное песочное Вишня', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Пирожное песочное Клубника со сливками', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Пирожное песочное Кокос', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Пирожное песочное лимонник', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Пирожное песочное с клубникой', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Пирожное песочное Творожный', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Пирожное песочное Трехслойник', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Пирог Клубника со сливками', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирог Кокосовый', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирог Абрикос', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирог Банан', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирог горбуша/рис', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирог Грибы/Капуста', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирог зелёный лук./яйцо', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирог Кальцоне (закрытый)', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирог капуста/яйцо', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирог Лимон', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирог мясо/рис', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирог рыбник', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирог с горбушей и рисом', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирог с грибами и капустой', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирог с зелёный луком и яйцом', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирог с капустой и яйцом', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирог с мясом и капустой', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирог с мясом и рисом', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирог с тыквой', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирог с яблоками и корицей', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирог Сметанник', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Пирог Творожник', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Пирог Трехслойник', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирог Тыква', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирог Чернослив', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пироговая посыпка (Штрейзель)', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирожок Тыква', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пирожок Яблоко Корица', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Плюшка с маком', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Пончик Банан', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Пончик Клубника', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Пончик', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Пончик с глазурью', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Пончики Берлинские с кремом', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Правильное печенье', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Расстегай', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Рогалик Банан', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Рогалик вареная сгущенка', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Рогалик Вишня', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Рогалик Чернослив', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Ромовая Баба', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Рыбник', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Сайка с изюмом', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Сайка сдобная', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Синнабон', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Слойка Абрикос', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Слойка Вишня', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Слойка грибы/сыр', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Слойка со сгущенкой', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Сметанник', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Солнышко', sheetType: 'pies', pointScope: 'point1' },
  { name: 'ТРАЙФАЛ', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Треугольник с мясом и картошкой', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Тыквенный', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Улитка с начинкой', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Хлеб 100% Ржаной', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Хлеб с изюмом и тмином', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Чебурек жареный', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Чиабатта', sheetType: 'pies', pointScope: 'point1' },
  { name: 'Шарлотка', sheetType: 'desserts', pointScope: 'both', shelfLifeDays: 5 },
  { name: 'Элеш с курицей', sheetType: 'pies', pointScope: 'point1' },
];
